/* soapH.h
   Generated by gSOAP 2.8.16 from googleapi.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data),0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (10)
#endif

#define soap_default_xsd__int(soap, a) soap_default_int(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_xsd__int
#define soap_write_xsd__int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_xsd__int(soap, data),0) || soap_put_xsd__int(soap, data, "xsd:int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_xsd__int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_xsd__int
#define soap_read_xsd__int(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data),0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_xsd__double
#define SOAP_TYPE_xsd__double (12)
#endif

#define soap_default_xsd__double(soap, a) soap_default_double(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_xsd__double(struct soap*, const char*, double *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__double(struct soap*, const double *, const char*, const char*);

#ifndef soap_write_xsd__double
#define soap_write_xsd__double(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_xsd__double(soap, data),0) || soap_put_xsd__double(soap, data, "xsd:double", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 double * SOAP_FMAC4 soap_get_xsd__double(struct soap*, double *, const char*, const char*);

#ifndef soap_read_xsd__double
#define soap_read_xsd__double(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__double(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);

#ifndef soap_write_double
#define soap_write_double(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_double(soap, data),0) || soap_put_double(soap, data, "double", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);

#ifndef soap_read_double
#define soap_read_double(soap, data) ( soap_begin_recv(soap) || !soap_get_double(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);

#ifndef soap_write_unsignedByte
#define soap_write_unsignedByte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_unsignedByte(soap, data),0) || soap_put_unsignedByte(soap, data, "unsignedByte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);

#ifndef soap_read_unsignedByte
#define soap_read_unsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);

#ifndef soap_write_unsignedInt
#define soap_write_unsignedInt(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_unsignedInt(soap, data),0) || soap_put_unsignedInt(soap, data, "unsignedInt", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);

#ifndef soap_read_unsignedInt
#define soap_read_unsignedInt(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedInt(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (9)
#endif

#define soap_default_xsd__boolean(soap, a) soap_default__Enum_1(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const enum _Enum_1 *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__boolean2s(struct soap*, enum _Enum_1);
SOAP_FMAC3 enum _Enum_1 * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, enum _Enum_1 *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__boolean(struct soap*, const char*, enum _Enum_1 *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const enum _Enum_1 *, const char*, const char*);

#ifndef soap_write_xsd__boolean
#define soap_write_xsd__boolean(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_xsd__boolean(soap, data),0) || soap_put_xsd__boolean(soap, data, "xsd:boolean", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 enum _Enum_1 * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, enum _Enum_1 *, const char*, const char*);

#ifndef soap_read_xsd__boolean
#define soap_read_xsd__boolean(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__boolean(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__Enum_1
#define SOAP_TYPE__Enum_1 (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__Enum_1(struct soap*, enum _Enum_1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__Enum_1(struct soap*, const char*, int, const enum _Enum_1 *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap__Enum_12s(struct soap*, enum _Enum_1);
SOAP_FMAC3 enum _Enum_1 * SOAP_FMAC4 soap_in__Enum_1(struct soap*, const char*, enum _Enum_1 *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2_Enum_1(struct soap*, const char*, enum _Enum_1 *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put__Enum_1(struct soap*, const enum _Enum_1 *, const char*, const char*);

#ifndef soap_write__Enum_1
#define soap_write__Enum_1(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__Enum_1(soap, data),0) || soap_put__Enum_1(soap, data, "Enum-1", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 enum _Enum_1 * SOAP_FMAC4 soap_get__Enum_1(struct soap*, enum _Enum_1 *, const char*, const char*);

#ifndef soap_read__Enum_1
#define soap_read__Enum_1(soap, data) ( soap_begin_recv(soap) || !soap_get__Enum_1(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data),0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data),0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data),0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data),0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data),0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_api__doSpellingSuggestion
#define SOAP_TYPE_api__doSpellingSuggestion (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_api__doSpellingSuggestion(struct soap*, struct api__doSpellingSuggestion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_api__doSpellingSuggestion(struct soap*, const struct api__doSpellingSuggestion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_api__doSpellingSuggestion(struct soap*, const char*, int, const struct api__doSpellingSuggestion *, const char*);
SOAP_FMAC3 struct api__doSpellingSuggestion * SOAP_FMAC4 soap_in_api__doSpellingSuggestion(struct soap*, const char*, struct api__doSpellingSuggestion *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_api__doSpellingSuggestion(struct soap*, const struct api__doSpellingSuggestion *, const char*, const char*);

#ifndef soap_write_api__doSpellingSuggestion
#define soap_write_api__doSpellingSuggestion(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_api__doSpellingSuggestion(soap, data),0) || soap_put_api__doSpellingSuggestion(soap, data, "api:doSpellingSuggestion", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct api__doSpellingSuggestion * SOAP_FMAC4 soap_get_api__doSpellingSuggestion(struct soap*, struct api__doSpellingSuggestion *, const char*, const char*);

#ifndef soap_read_api__doSpellingSuggestion
#define soap_read_api__doSpellingSuggestion(soap, data) ( soap_begin_recv(soap) || !soap_get_api__doSpellingSuggestion(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_api__doSpellingSuggestionResponse
#define SOAP_TYPE_api__doSpellingSuggestionResponse (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_api__doSpellingSuggestionResponse(struct soap*, struct api__doSpellingSuggestionResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_api__doSpellingSuggestionResponse(struct soap*, const struct api__doSpellingSuggestionResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_api__doSpellingSuggestionResponse(struct soap*, const char*, int, const struct api__doSpellingSuggestionResponse *, const char*);
SOAP_FMAC3 struct api__doSpellingSuggestionResponse * SOAP_FMAC4 soap_in_api__doSpellingSuggestionResponse(struct soap*, const char*, struct api__doSpellingSuggestionResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_api__doSpellingSuggestionResponse(struct soap*, const struct api__doSpellingSuggestionResponse *, const char*, const char*);

#ifndef soap_write_api__doSpellingSuggestionResponse
#define soap_write_api__doSpellingSuggestionResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_api__doSpellingSuggestionResponse(soap, data),0) || soap_put_api__doSpellingSuggestionResponse(soap, data, "api:doSpellingSuggestionResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct api__doSpellingSuggestionResponse * SOAP_FMAC4 soap_get_api__doSpellingSuggestionResponse(struct soap*, struct api__doSpellingSuggestionResponse *, const char*, const char*);

#ifndef soap_read_api__doSpellingSuggestionResponse
#define soap_read_api__doSpellingSuggestionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_api__doSpellingSuggestionResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_api__doGetCachedPage
#define SOAP_TYPE_api__doGetCachedPage (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_api__doGetCachedPage(struct soap*, struct api__doGetCachedPage *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_api__doGetCachedPage(struct soap*, const struct api__doGetCachedPage *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_api__doGetCachedPage(struct soap*, const char*, int, const struct api__doGetCachedPage *, const char*);
SOAP_FMAC3 struct api__doGetCachedPage * SOAP_FMAC4 soap_in_api__doGetCachedPage(struct soap*, const char*, struct api__doGetCachedPage *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_api__doGetCachedPage(struct soap*, const struct api__doGetCachedPage *, const char*, const char*);

#ifndef soap_write_api__doGetCachedPage
#define soap_write_api__doGetCachedPage(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_api__doGetCachedPage(soap, data),0) || soap_put_api__doGetCachedPage(soap, data, "api:doGetCachedPage", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct api__doGetCachedPage * SOAP_FMAC4 soap_get_api__doGetCachedPage(struct soap*, struct api__doGetCachedPage *, const char*, const char*);

#ifndef soap_read_api__doGetCachedPage
#define soap_read_api__doGetCachedPage(soap, data) ( soap_begin_recv(soap) || !soap_get_api__doGetCachedPage(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_api__doGetCachedPageResponse
#define SOAP_TYPE_api__doGetCachedPageResponse (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_api__doGetCachedPageResponse(struct soap*, struct api__doGetCachedPageResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_api__doGetCachedPageResponse(struct soap*, const struct api__doGetCachedPageResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_api__doGetCachedPageResponse(struct soap*, const char*, int, const struct api__doGetCachedPageResponse *, const char*);
SOAP_FMAC3 struct api__doGetCachedPageResponse * SOAP_FMAC4 soap_in_api__doGetCachedPageResponse(struct soap*, const char*, struct api__doGetCachedPageResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_api__doGetCachedPageResponse(struct soap*, const struct api__doGetCachedPageResponse *, const char*, const char*);

#ifndef soap_write_api__doGetCachedPageResponse
#define soap_write_api__doGetCachedPageResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_api__doGetCachedPageResponse(soap, data),0) || soap_put_api__doGetCachedPageResponse(soap, data, "api:doGetCachedPageResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct api__doGetCachedPageResponse * SOAP_FMAC4 soap_get_api__doGetCachedPageResponse(struct soap*, struct api__doGetCachedPageResponse *, const char*, const char*);

#ifndef soap_read_api__doGetCachedPageResponse
#define soap_read_api__doGetCachedPageResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_api__doGetCachedPageResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_api__doGoogleSearch
#define SOAP_TYPE_api__doGoogleSearch (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_api__doGoogleSearch(struct soap*, struct api__doGoogleSearch *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_api__doGoogleSearch(struct soap*, const struct api__doGoogleSearch *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_api__doGoogleSearch(struct soap*, const char*, int, const struct api__doGoogleSearch *, const char*);
SOAP_FMAC3 struct api__doGoogleSearch * SOAP_FMAC4 soap_in_api__doGoogleSearch(struct soap*, const char*, struct api__doGoogleSearch *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_api__doGoogleSearch(struct soap*, const struct api__doGoogleSearch *, const char*, const char*);

#ifndef soap_write_api__doGoogleSearch
#define soap_write_api__doGoogleSearch(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_api__doGoogleSearch(soap, data),0) || soap_put_api__doGoogleSearch(soap, data, "api:doGoogleSearch", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct api__doGoogleSearch * SOAP_FMAC4 soap_get_api__doGoogleSearch(struct soap*, struct api__doGoogleSearch *, const char*, const char*);

#ifndef soap_read_api__doGoogleSearch
#define soap_read_api__doGoogleSearch(soap, data) ( soap_begin_recv(soap) || !soap_get_api__doGoogleSearch(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_api__doGoogleSearchResponse
#define SOAP_TYPE_api__doGoogleSearchResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_api__doGoogleSearchResponse(struct soap*, struct api__doGoogleSearchResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_api__doGoogleSearchResponse(struct soap*, const struct api__doGoogleSearchResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_api__doGoogleSearchResponse(struct soap*, const char*, int, const struct api__doGoogleSearchResponse *, const char*);
SOAP_FMAC3 struct api__doGoogleSearchResponse * SOAP_FMAC4 soap_in_api__doGoogleSearchResponse(struct soap*, const char*, struct api__doGoogleSearchResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_api__doGoogleSearchResponse(struct soap*, const struct api__doGoogleSearchResponse *, const char*, const char*);

#ifndef soap_write_api__doGoogleSearchResponse
#define soap_write_api__doGoogleSearchResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_api__doGoogleSearchResponse(soap, data),0) || soap_put_api__doGoogleSearchResponse(soap, data, "api:doGoogleSearchResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct api__doGoogleSearchResponse * SOAP_FMAC4 soap_get_api__doGoogleSearchResponse(struct soap*, struct api__doGoogleSearchResponse *, const char*, const char*);

#ifndef soap_read_api__doGoogleSearchResponse
#define soap_read_api__doGoogleSearchResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_api__doGoogleSearchResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_api__GoogleSearchResult
#define SOAP_TYPE_api__GoogleSearchResult (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_api__GoogleSearchResult(struct soap*, struct api__GoogleSearchResult *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_api__GoogleSearchResult(struct soap*, const struct api__GoogleSearchResult *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_api__GoogleSearchResult(struct soap*, const char*, int, const struct api__GoogleSearchResult *, const char*);
SOAP_FMAC3 struct api__GoogleSearchResult * SOAP_FMAC4 soap_in_api__GoogleSearchResult(struct soap*, const char*, struct api__GoogleSearchResult *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_api__GoogleSearchResult(struct soap*, const struct api__GoogleSearchResult *, const char*, const char*);

#ifndef soap_write_api__GoogleSearchResult
#define soap_write_api__GoogleSearchResult(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_api__GoogleSearchResult(soap, data),0) || soap_put_api__GoogleSearchResult(soap, data, "api:GoogleSearchResult", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct api__GoogleSearchResult * SOAP_FMAC4 soap_get_api__GoogleSearchResult(struct soap*, struct api__GoogleSearchResult *, const char*, const char*);

#ifndef soap_read_api__GoogleSearchResult
#define soap_read_api__GoogleSearchResult(soap, data) ( soap_begin_recv(soap) || !soap_get_api__GoogleSearchResult(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ResultElementArray
#define SOAP_TYPE_ResultElementArray (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ResultElementArray(struct soap*, struct ResultElementArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ResultElementArray(struct soap*, struct ResultElementArray const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ResultElementArray(struct soap*, const char*, int, const struct ResultElementArray *, const char*);
SOAP_FMAC3 struct ResultElementArray * SOAP_FMAC4 soap_in_ResultElementArray(struct soap*, const char*, struct ResultElementArray *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ResultElementArray(struct soap*, const struct ResultElementArray *, const char*, const char*);

#ifndef soap_write_ResultElementArray
#define soap_write_ResultElementArray(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ResultElementArray(soap, data),0) || soap_put_ResultElementArray(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ResultElementArray * SOAP_FMAC4 soap_get_ResultElementArray(struct soap*, struct ResultElementArray *, const char*, const char*);

#ifndef soap_read_ResultElementArray
#define soap_read_ResultElementArray(soap, data) ( soap_begin_recv(soap) || !soap_get_ResultElementArray(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_api__ResultElement
#define SOAP_TYPE_api__ResultElement (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_api__ResultElement(struct soap*, struct api__ResultElement *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_api__ResultElement(struct soap*, const struct api__ResultElement *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_api__ResultElement(struct soap*, const char*, int, const struct api__ResultElement *, const char*);
SOAP_FMAC3 struct api__ResultElement * SOAP_FMAC4 soap_in_api__ResultElement(struct soap*, const char*, struct api__ResultElement *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_api__ResultElement(struct soap*, const struct api__ResultElement *, const char*, const char*);

#ifndef soap_write_api__ResultElement
#define soap_write_api__ResultElement(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_api__ResultElement(soap, data),0) || soap_put_api__ResultElement(soap, data, "api:ResultElement", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct api__ResultElement * SOAP_FMAC4 soap_get_api__ResultElement(struct soap*, struct api__ResultElement *, const char*, const char*);

#ifndef soap_read_api__ResultElement
#define soap_read_api__ResultElement(soap, data) ( soap_begin_recv(soap) || !soap_get_api__ResultElement(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_DirectoryCategoryArray
#define SOAP_TYPE_DirectoryCategoryArray (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_DirectoryCategoryArray(struct soap*, struct DirectoryCategoryArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_DirectoryCategoryArray(struct soap*, struct DirectoryCategoryArray const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_DirectoryCategoryArray(struct soap*, const char*, int, const struct DirectoryCategoryArray *, const char*);
SOAP_FMAC3 struct DirectoryCategoryArray * SOAP_FMAC4 soap_in_DirectoryCategoryArray(struct soap*, const char*, struct DirectoryCategoryArray *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_DirectoryCategoryArray(struct soap*, const struct DirectoryCategoryArray *, const char*, const char*);

#ifndef soap_write_DirectoryCategoryArray
#define soap_write_DirectoryCategoryArray(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_DirectoryCategoryArray(soap, data),0) || soap_put_DirectoryCategoryArray(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct DirectoryCategoryArray * SOAP_FMAC4 soap_get_DirectoryCategoryArray(struct soap*, struct DirectoryCategoryArray *, const char*, const char*);

#ifndef soap_read_DirectoryCategoryArray
#define soap_read_DirectoryCategoryArray(soap, data) ( soap_begin_recv(soap) || !soap_get_DirectoryCategoryArray(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_api__DirectoryCategory
#define SOAP_TYPE_api__DirectoryCategory (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_api__DirectoryCategory(struct soap*, struct api__DirectoryCategory *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_api__DirectoryCategory(struct soap*, const struct api__DirectoryCategory *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_api__DirectoryCategory(struct soap*, const char*, int, const struct api__DirectoryCategory *, const char*);
SOAP_FMAC3 struct api__DirectoryCategory * SOAP_FMAC4 soap_in_api__DirectoryCategory(struct soap*, const char*, struct api__DirectoryCategory *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_api__DirectoryCategory(struct soap*, const struct api__DirectoryCategory *, const char*, const char*);

#ifndef soap_write_api__DirectoryCategory
#define soap_write_api__DirectoryCategory(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_api__DirectoryCategory(soap, data),0) || soap_put_api__DirectoryCategory(soap, data, "api:DirectoryCategory", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct api__DirectoryCategory * SOAP_FMAC4 soap_get_api__DirectoryCategory(struct soap*, struct api__DirectoryCategory *, const char*, const char*);

#ifndef soap_read_api__DirectoryCategory
#define soap_read_api__DirectoryCategory(soap, data) ( soap_begin_recv(soap) || !soap_get_api__DirectoryCategory(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__base64Binary(struct soap*, struct xsd__base64Binary *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__base64Binary(struct soap*, struct xsd__base64Binary const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const struct xsd__base64Binary *, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__base64Binary(struct soap*, const struct xsd__base64Binary *, const char*, const char*);

#ifndef soap_write_xsd__base64Binary
#define soap_write_xsd__base64Binary(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_xsd__base64Binary(soap, data),0) || soap_put_xsd__base64Binary(soap, data, "xsd:base64Binary", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, struct xsd__base64Binary *, const char*, const char*);

#ifndef soap_read_xsd__base64Binary
#define soap_read_xsd__base64Binary(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__base64Binary(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data),0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data),0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data),0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerToxsd__string
#define SOAP_TYPE_PointerToxsd__string (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__string(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__string(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerToxsd__string(struct soap*, const char*, char ***, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__string(struct soap*, char **const*, const char*, const char*);

#ifndef soap_write_PointerToxsd__string
#define soap_write_PointerToxsd__string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToxsd__string(soap, data),0) || soap_put_PointerToxsd__string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerToxsd__string(struct soap*, char ***, const char*, const char*);

#ifndef soap_read_PointerToxsd__string
#define soap_read_PointerToxsd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToxsd__string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerToxsd__base64Binary
#define SOAP_TYPE_PointerToxsd__base64Binary (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__base64Binary(struct soap*, const char *, int, struct xsd__base64Binary *const*, const char *);
SOAP_FMAC3 struct xsd__base64Binary ** SOAP_FMAC4 soap_in_PointerToxsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary *const*, const char*, const char*);

#ifndef soap_write_PointerToxsd__base64Binary
#define soap_write_PointerToxsd__base64Binary(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToxsd__base64Binary(soap, data),0) || soap_put_PointerToxsd__base64Binary(soap, data, "xsd:base64Binary", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct xsd__base64Binary ** SOAP_FMAC4 soap_get_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary **, const char*, const char*);

#ifndef soap_read_PointerToxsd__base64Binary
#define soap_read_PointerToxsd__base64Binary(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToxsd__base64Binary(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerToapi__doGoogleSearchResponse
#define SOAP_TYPE_PointerToapi__doGoogleSearchResponse (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToapi__doGoogleSearchResponse(struct soap*, struct api__doGoogleSearchResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToapi__doGoogleSearchResponse(struct soap*, const char *, int, struct api__doGoogleSearchResponse *const*, const char *);
SOAP_FMAC3 struct api__doGoogleSearchResponse ** SOAP_FMAC4 soap_in_PointerToapi__doGoogleSearchResponse(struct soap*, const char*, struct api__doGoogleSearchResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToapi__doGoogleSearchResponse(struct soap*, struct api__doGoogleSearchResponse *const*, const char*, const char*);

#ifndef soap_write_PointerToapi__doGoogleSearchResponse
#define soap_write_PointerToapi__doGoogleSearchResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToapi__doGoogleSearchResponse(soap, data),0) || soap_put_PointerToapi__doGoogleSearchResponse(soap, data, "api:doGoogleSearchResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct api__doGoogleSearchResponse ** SOAP_FMAC4 soap_get_PointerToapi__doGoogleSearchResponse(struct soap*, struct api__doGoogleSearchResponse **, const char*, const char*);

#ifndef soap_read_PointerToapi__doGoogleSearchResponse
#define soap_read_PointerToapi__doGoogleSearchResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToapi__doGoogleSearchResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerToapi__ResultElement
#define SOAP_TYPE_PointerToapi__ResultElement (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToapi__ResultElement(struct soap*, struct api__ResultElement *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToapi__ResultElement(struct soap*, const char *, int, struct api__ResultElement *const*, const char *);
SOAP_FMAC3 struct api__ResultElement ** SOAP_FMAC4 soap_in_PointerToapi__ResultElement(struct soap*, const char*, struct api__ResultElement **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToapi__ResultElement(struct soap*, struct api__ResultElement *const*, const char*, const char*);

#ifndef soap_write_PointerToapi__ResultElement
#define soap_write_PointerToapi__ResultElement(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToapi__ResultElement(soap, data),0) || soap_put_PointerToapi__ResultElement(soap, data, "api:ResultElement", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct api__ResultElement ** SOAP_FMAC4 soap_get_PointerToapi__ResultElement(struct soap*, struct api__ResultElement **, const char*, const char*);

#ifndef soap_read_PointerToapi__ResultElement
#define soap_read_PointerToapi__ResultElement(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToapi__ResultElement(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerToapi__DirectoryCategory
#define SOAP_TYPE_PointerToapi__DirectoryCategory (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToapi__DirectoryCategory(struct soap*, struct api__DirectoryCategory *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToapi__DirectoryCategory(struct soap*, const char *, int, struct api__DirectoryCategory *const*, const char *);
SOAP_FMAC3 struct api__DirectoryCategory ** SOAP_FMAC4 soap_in_PointerToapi__DirectoryCategory(struct soap*, const char*, struct api__DirectoryCategory **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToapi__DirectoryCategory(struct soap*, struct api__DirectoryCategory *const*, const char*, const char*);

#ifndef soap_write_PointerToapi__DirectoryCategory
#define soap_write_PointerToapi__DirectoryCategory(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToapi__DirectoryCategory(soap, data),0) || soap_put_PointerToapi__DirectoryCategory(soap, data, "api:DirectoryCategory", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct api__DirectoryCategory ** SOAP_FMAC4 soap_get_PointerToapi__DirectoryCategory(struct soap*, struct api__DirectoryCategory **, const char*, const char*);

#ifndef soap_read_PointerToapi__DirectoryCategory
#define soap_read_PointerToapi__DirectoryCategory(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToapi__DirectoryCategory(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);

#ifndef soap_write_PointerTounsignedByte
#define soap_write_PointerTounsignedByte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTounsignedByte(soap, data),0) || soap_put_PointerTounsignedByte(soap, data, "unsignedByte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);

#ifndef soap_read_PointerTounsignedByte
#define soap_read_PointerTounsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTounsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (7)
#endif

#define soap_default_xsd__string(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_xsd__string
#define soap_write_xsd__string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_xsd__string(soap, data),0) || soap_put_xsd__string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_xsd__string
#define soap_read_xsd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data),0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data),0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
